version: '3'
services:
  nginx:
#    image: tekn0ir/nginx-stream
#    image: hokaccha/grpc-web-proxy-nginx:latest
    image: nginx:1.20.0
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "52200:52200"
      - "50052:50052"
      - "8080:8080"
    depends_on:
      - grpc
      - grpc1
      - grpc2
#    command: /bin/sh -c "envsubst '$$NGINX_GRPC_PASS' < /etc/nginx/conf.d/grpc_proxy.conf.template > /etc/nginx/conf.d/grpc_proxy.conf && nginx -g 'daemon off;'"
#    environment:
#      NGINX_GRPC_PASS: 'grpc_consumer_1:8080'
    networks:
      - zmq_ingressor

  grpc:
    image: ubuntu:20.04
    container_name: grpc
    volumes:
      - ../../cmake-build-release/bin:/home/zero/bin
    command:
      ["/bin/bash", "-c", "/home/zero/bin/try_grpc_server"]
    networks:
      - zmq_ingressor

  grpc1:
    image: ubuntu:20.04
    container_name: grpc1
    volumes:
      - ../../cmake-build-release/bin:/home/zero/bin
    command:
      ["/bin/bash", "-c", "/home/zero/bin/try_grpc_server"]
    networks:
      - zmq_ingressor

  grpc2:
    image: ubuntu:20.04
    container_name: grpc2
    volumes:
      - ../../cmake-build-release/bin:/home/zero/bin
    command:
      ["/bin/bash", "-c", "/home/zero/bin/try_grpc_server"]
    networks:
      - zmq_ingressor

networks:
  zmq_ingressor: