name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: configure
#       run: ./configure
    - name: make flatbuffer generated files
      run: make flat
    - name: make release
      run: make build-release
#     - name: run benchmarks
#       run: make benchmarks
